---
- name: Configure PostgreSQL for replication (Primary)
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#wal_level', line: 'wal_level = logical' }
    - { regexp: '^#wal_log_hints',  line : 'wal_log_hints = on'}
    - { regexp: '^#max_wal_senders', line: 'max_wal_senders = 5' }
    - { regexp: '^#listen_addresses', line: "listen_addresses = '*'" }

- name: Allow replication connections from replicas (Primary)
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    line: "host replication all {{ item }}/32 md5"
  loop: "{{ groups['replicas'] | map('extract', hostvars, 'ansible_host') | list }}"


- name: Create replication user
  postgresql_user:
    state: present
    name: replica_user
    password: replica_password
    role_attr_flags: REPLICATION
  become: true
  become_user: postgres

- name: Restart PostgreSQL to apply changes
  systemd:
    name: postgresql
    state: restarted


