---
- name: Stop PostgreSQL service on replica
  systemd:
    name: postgresql
    state: stopped

- name: Clear existing PostgreSQL data directory
  file:
    path: /var/lib/postgresql/16/main
    state: absent
  become: true

- name: Set replication slot name
  set_fact:
    replication_slot_name: "replica_{{ inventory_hostname | regex_replace('-', '_') }}"

- name: Copy data from primary node
  command: >
    pg_basebackup -h {{ hostvars['primary-db'].ansible_host }} -U replica_user -X stream -C -S {{ replication_slot_name }} -v -R -D /var/lib/postgresql/16/main/
  become: true  # Keep this for running with sudo permissions
  environment:
    PGPASSWORD: 'replica_password'
 
    
- name: Ensure correct ownership of the PostgreSQL data directory
  file:
    path: /var/lib/postgresql/16/main
    state: directory
    owner: postgres
    group: postgres
    recurse: yes
  become: true

- name: Start PostgreSQL service on replica
  systemd:
    name: postgresql
    state: started

