---
# Tasks for installing PostgreSQL using Ubuntu's default repositories
- name: Update the package index
  apt:
    update_cache: yes

- name: Install PostgreSQL and contrib package
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present

- name: Ensure PostgreSQL is running and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes

