---
- name: Setup PostgreSQL on All Servers
  hosts: all  # Targets both primary and replica hosts
  become: yes
  tasks:
    - name: Install PostgreSQL
      include_tasks: tasks/install.yml  # Install PostgreSQL on all servers

- name: Apply PostgreSQL configuration
  hosts: all
  become: yes
  tasks:
    - include_tasks: tasks/configure_postgres.yml # Configure params like max_conn and shared buffers

- name: Configure PostgreSQL Primary
  hosts: primary-db
  become: yes
  tasks:
    - include_tasks: tasks/configure_primary.yml  # Configure primary PostgreSQL

- name: Configure PostgreSQL Replicas
  hosts: replica-db1, replica-db2
  become: yes
  tasks:
    - include_tasks: tasks/configure_replica.yml  # Configure replicas


